name: Build Test
on:
  push:
    branches-ignore: main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4

      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      # - name: Cache Node Modules
      #   uses: actions/cache@v4
      #   id: node_modules_cache_id
      #   env:
      #     cache-name: cache node_modules
      #   with:
      #     path: "**/node_modules"
      #     key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Dependences Install
        # if: ${{ steps.node_modules_cache_id.outputs.cache-hit != 'true' }}
        run: pnpm install

      - name: Build
        run: pnpm build
